# This list of crons get applied ONLY to UAT hosts.  
# This should only be used for things VERY specific to only this environment.

#ausftp_crons_uat:
#  - name: example
#    user: example3
#    comment: "This is just an example, only for demonstration.. this comment line is not used, just for info"
#    minute: "28"
#    hour: "9"
#    job: "touch /tmp/example3_cron"
   
