shyweb_westpac_url: shy.onlineinvesting.westpac.com.au
shyweb_webiress_url: p1.webiress.onlineinvesting.westpac.com.au

sshd_config_ClientAliveCountMax: 15

wmaster_ssh_key: |
  {{ ssh_key_shyapps_sysmgt }}
  {{ ssh_key_teamcity_agent }}

elastic_token: "{{ elastic_tokens.linux_shyweb_prod }}"
