# Used to conveniently generate a hashed password to be allocated.  This will commonly be used only for service accounts that require a 
# password.
#
# To generate a hashed password (also sometimes called a shadow password)
#    ansible-playbook playbooks/password.yaml
#
# The hashed item can then be used by the ansible.builtin.user module to set the password (which essentially puts it in the /etc/shadow file)
#
- name: Generate a password hash
  become: no
  hosts: localhost

  vars_prompt:
    - name: mypassword
      prompt: "Enter Password"

  tasks:
    - debug:
        msg: "{{ mypassword | password_hash('sha512') }}"
