# The purpose of this is to call all the related playbooks to deploy security/compliance standards accross all our environments.
# the playbooks will be seperated based on functionality, just to keep things simpler to maintain.
# 
# It is also very likely that automated processes will be installed which will run this playbook regularly to ensure the servers maintain 
# stability and consitency across our entire infrastructure (similar to what puppet did previously).
#
# NOTE that the playbooks will be executed in the order they are listed.
---

#- import_playbook: base_storage.yaml
#- import_playbook: base_system_accounts.yaml
#- import_playbook: base_dmz_local_accounts.yaml
#- import_playbook: base_resolv.yaml
#- import_playbook: base_certificate_chains.yaml
#- import_playbook: base_satellite.yaml
#- import_playbook: base_puppet.yaml
#- import_playbook: base_repos.yaml
#- import_playbook: base_packages.yaml
#- import_playbook: base_deploy_certs.yaml
#- import_playbook: base_realmd.yaml
#- import_playbook: base_ntp.yaml
#- import_playbook: base_bash_prompt.yaml
#- import_playbook: base_general.yaml
#- import_playbook: base_firewalld_services.yaml
#- import_playbook: base_nrpe.yaml
- import_playbook: base_ssh.yaml

- import_playbook: base_ansible.yaml
- import_playbook: base_shyny.yaml
- import_playbook: base_shy_devel.yaml
- import_playbook: base_appproxy.yaml
- import_playbook: base_ausftp.yaml
- import_playbook: base_shyweb.yaml

- import_playbook: base_elastic.yaml
- import_playbook: base_nessus.yaml
- import_playbook: base_xdr.yaml
- import_playbook: base_cleanup.yaml

...
