# Used to conveniently generate a hashed password, and apply it to target servers.
# This will commonly be used only for service accounts that require a 
# password.
#
# This is normally only used to change a password for the same account on multiple machines.
- name: Set password on local accounts.
  become: yes
  hosts: "{{ ansible_limit | default(omit) }}"

  vars_prompt:
    - name: myaccount
      private: false
      prompt: "Enter Account"

    - name: mypassword
      prompt: "Enter Password"

  vars:
    pass_hash: "{{ mypassword | password_hash('sha512') }}"

  tasks:
    - debug:
        msg: "{{ pass_hash }}"

    - debug:
        msg: "{{ pass_hash }}"

    - name: Set Expire
      shell:
        cmd: "passwd -x {{ expire | default('99999') }} {{ myaccount }}"
        warn: false
      changed_when: false
      ignore_errors: true

    - name: "Set Password for: {{ myaccount }}"
      user:
        name: "{{ myaccount }}"
        password: "{{ pass_hash }}"
        
